### PR TITLE
New sem ui

### PR DESCRIPTION
**Pull request by Arthurlpgc**

### CODE REVIEW

**Comment by ramonsaboya** [comment]
Seems good, but please include screenshots. What about having the sign in/out on the bottom of the bar?

**Comment by Arthurlpgc** [comment]
Screen Shot 2019-10-06 at 11 05 12 PM
Screen Shot 2019-10-06 at 11 05 26 PM
Screen Shot 2019-10-06 at 11 05 35 PM

**Comment by Arthurlpgc** [comment]
Screen Shot 2019-10-06 at 11 05 49 PM
Screen Shot 2019-10-06 at 11 07 42 PM
Screen Shot 2019-10-06 at 11 09 16 PM

**Comment by Arthurlpgc** [comment]
Screen Shot 2019-10-06 at 11 21 54 PM

**Pull request closed without merging**
