### PR TITLE
Use env to serve page statically

### PR DESCRIPTION
**Pull request by Arthurlpgc**

### CODE REVIEW

**Comment by RamonSaboya** [comment]
I think we should be using nginx to serve static files directly, it should be way faster

**Comment by RamonSaboya** [comment]
> I think we should be using nginx to serve static files directly, it should be way faster

A docker multi-stage build seems like the way to go here

**Comment by Arthurlpgc** [comment]
> I think we should be using nginx to serve static files directly, it should be way faster

I will work on it soon

**Comment by Arthurlpgc** [comment]
> I think we should be using nginx to serve static files directly, it should be way faster

The complexity might be too big for not a good enough advantage at this point, maybe open a wishlist issue..

**Comment by RamonSaboya** [comment]
> > I think we should be using nginx to serve static files directly, it should be way faster
> 
> The complexity might be too big for not a good enough advantage at this point, maybe open a wishlist issue..

I don't think it would be that much trouble, probably adding 5 lines to the current Dockerfile would probably be enough. I am not sure what are the performance benefits of using nginx directly, but IMO we should optimize wherever we can, so that we can spend less resources.

I think Dockerfile would look close to this:
```
FROM node:11.14-slim as react-build
WORKDIR /project
COPY package.json yarn.lock ./
RUN yarn
COPY . .
RUN yarn build

FROM nginx
COPY --from=react-build /project/build/ /usr/share/nginx/html
COPY --from=react-build /project/nginx.conf /etc/nginx/conf.d/default.conf
```
We would also need to provide the nginx.conf config file.

**Pull request merged**
